Hm 13 AdminService 수정
Hwamok/Hwamok-api-server pull request #12
Opened 2023-11-17 04:18 UTC by changgyu-kim

1. @Transitional 추가
2. 리스트조회 어드민정보 없을 시 검증로직 추가
3. 의미없는 공백 및 코드정

2023-11-17 09:14 UTC, goyounha11 requested changes

2023-11-17 09:14 UTC, goyounha11 commented on src/test/java/com/hwamok/admin/service/AdminServiceImplTest.java
p라고 네이밍이되면 저  p가 뭔지 알수없을것같은데요 밑에서는용

2023-11-17 11:40 UTC, changgyu-kim commented on src/test/java/com/hwamok/admin/service/AdminServiceImplTest.java
생각이 짧았네요.. 알아볼수있게 변경했습니다

2023-11-18 09:23 UTC, goyounha11 approved these changes

2023-11-18 12:36 UTC, GlenJeong approved these changes

2023-11-20 14:08 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/admin/service/AdminServiceImpl.java
여기 공백있어요!

2023-11-20 14:08 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/admin/service/AdminServiceImplTest.java
여기도 공백있어요!

2023-11-20 15:35 UTC, changgyu-kim commented on src/main/java/com/hwamok/admin/service/AdminServiceImpl.java
네 수정했습니다!

2023-11-20 15:35 UTC, changgyu-kim commented on src/test/java/com/hwamok/admin/service/AdminServiceImplTest.java
네 수정했습니다!

2023-11-20 16:21 UTC, LeeAYoung1207 approved these changes

2023-11-21 06:58 UTC, merged