HM-14 AdminContoller 수정
Hwamok/Hwamok-api-server pull request #13
Opened 2023-11-17 04:37 UTC by changgyu-kim

1. AdminReadDto 추가
2. Admin 조회 시 Dto로 반환
3. 의미없는 공백 정리

2023-11-17 09:12 UTC, goyounha11 requested changes

2023-11-17 09:12 UTC, goyounha11 commented on src/main/java/com/hwamok/api/AdminController.java
> +        }
@changgyu-kim 이거 아주 멋있게 처리하는 방법이 있습니다.
stream에 대해 공부하시고 적용해주세요.

2023-11-17 09:12 UTC, goyounha11 commented on src/main/java/com/hwamok/notice/domain/Notice.java
> +  private NoticeStatus status = NoticeStatus.CREATED;
lenth없어도되나요?

2023-11-17 12:48 UTC, changgyu-kim commented on src/main/java/com/hwamok/notice/domain/Notice.java
> +  private NoticeStatus status = NoticeStatus.CREATED;
Notice도메인을 브런치를 따로 빼지않고 이곳에 잘못올려서 다시 원래대로 돌리려 삭제했습니다. Notice도메인 개발브런치에서 적용하겠습니다.

2023-11-17 12:48 UTC, changgyu-kim commented on src/main/java/com/hwamok/api/AdminController.java
> +        }
스트림 멋지게 적용해보았습니다

2023-11-17 16:55 UTC, goyounha11 commented on src/main/java/com/hwamok/api/AdminController.java
> +        }
더 멋있는 방법이 있습니다~! 공부해보시죠! 키워드는 map

2023-11-18 12:21 UTC, LeeAYoung1207 approved these changes
제눈엔 엄청 잘만드셨는데, 아직 쩌로님눈엔 부족한게 많나보네요...ㅎㅎㅎ
응답DTO까지 만드시고 고생많으셨어요..!

2023-11-18 15:43 UTC, changgyu-kim commented on src/main/java/com/hwamok/api/AdminController.java
> +        }
map 적용하여 바로 타입변환해서 Dto에 담을 수 있네요! 수정완료했습니다.

2023-11-19 06:07 UTC, goyounha11 commented on src/main/java/com/hwamok/api/AdminController.java
> +                                                            .collect(Collectors.toList());
```
    @Override
    public List<AdminReadDto.Response> getInfos() {
        List<Admin> adminList = adminRepository.findAll();

        PreConditions.validate(adminList.size() != 0, ExceptionCode.NOT_FOUND_ADMIN);

        return adminList.stream().map(AdminReadDto.Response::new).toList();
    }
```

이렇게 서비스를 바꿔주세요.

2023-11-19 06:08 UTC, goyounha11 commented on src/main/java/com/hwamok/api/AdminController.java
> +                                                            .collect(Collectors.toList());
지금 서비스를 보니까 findall을 두번하고있고 스트림 자체를 비니지스해서 해도 좋을것같습니다.

2023-11-19 06:34 UTC, changgyu-kim commented on src/main/java/com/hwamok/api/AdminController.java
> +                                                            .collect(Collectors.toList());
findAll 두번호출 수정 및 말씀해주신 사항처럼 서비스에서 스트림 사용하여 적용하였습니다

2023-11-20 08:00 UTC, goyounha11 approved these changes

2023-11-20 15:53 UTC, GlenJeong approved these changes

2023-11-20 15:53 UTC, GlenJeong commented
수고했어요~

2023-11-20 16:12 UTC, merged