Hm 15 Notice 도메인 개발
Hwamok/Hwamok-api-server pull request #14
Opened 2023-11-17 13:32 UTC by changgyu-kim

2023-11-18 09:19 UTC, goyounha11 requested changes

2023-11-18 09:19 UTC, goyounha11 commented on src/main/java/com/hwamok/notice/domain/Notice.java
> +  @Length(max = 1000)
colunm length 사용안하시는 이유가 있나요?

2023-11-18 09:19 UTC, goyounha11 commented on build.gradle
> +    implementation 'org.hibernate.validator:hibernate-validator:8.0.1.Final'
이런 의존성을 추가할때는 팀원들과 협의가 되어야하는데 협의 되었나요?

2023-11-18 09:19 UTC, goyounha11 commented on src/main/java/com/hwamok/notice/domain/Notice.java
> +    require(content.length() <= 1000);
같은 require인데 공백 필요없어 보입니다.

2023-11-18 09:19 UTC, goyounha11 commented on src/test/java/com/hwamok/notice/domain/NoticeRepositoryTest.java
> +
스태틱 임포트 해주시죠

2023-11-18 09:19 UTC, goyounha11 commented on src/test/java/com/hwamok/notice/domain/NoticeTest.java
> +        Admin admin = AdminFixture.createAdmin();
스태틱 임포트 해주시고 이렇게 보니까 fakeTitle이 좀 멋이 없네요
여러곳에서 쓰일 것 같으니 randomUtils이런거 하나 만들어서 인자로 생성될 글자 수 입력하면 랜덤으로 지정된 렝스만큼 자동 생성되는 함수 하나 만들어보죠

2023-11-18 09:19 UTC, goyounha11 commented on src/test/java/com/hwamok/notice/domain/NoticeTest.java
> +        String fakeContent = "내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내
ㄷㄷ

2023-11-18 12:28 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/notice/domain/Notice.java
> +    require(content.length() <= 1000);
title, content 길이같은경우에는 exceptionCode 추가해서 validate로 넣는게 더낫지 않을까요?
제 생각에는 똑같이 require로 쓰면, 추후 에러가 illegalArgumentException만 뜨고 세부 이유가 나오지 않아서, 값이 안들어간건지, 길이가 부족한건지 어떤이유때문에 문제생긴건지를 잘 모를것같아요...

2023-11-18 15:50 UTC, changgyu-kim commented on src/main/java/com/hwamok/notice/domain/Notice.java
> +  @Length(max = 1000)
content 에 내용이 1000자 이내로 작성되게 만들고싶어서 columnDefinition = "TEXT" 지정했더니 length가 적용되지않았습니다.   그래서 @Length를 활용했습니다.

2023-11-18 17:02 UTC, changgyu-kim commented on src/main/java/com/hwamok/notice/domain/Notice.java
> +    require(content.length() <= 1000);
길이같은 경우에는 유효성검사 대상이 아닌 DB에 들어갈 필수조건이기때문에  require을 사용했었는데  REQUIRED_PARAMETER를 반환하니 예외원인를 알 수 없겠네요.. validate로 수정하였습니다.

2023-11-18 17:02 UTC, changgyu-kim commented on src/test/java/com/hwamok/notice/domain/NoticeRepositoryTest.java
> +
수정하였습니다

2023-11-18 17:02 UTC, changgyu-kim commented on src/test/java/com/hwamok/notice/domain/NoticeTest.java
> +        Admin admin = AdminFixture.createAdmin();
유틸클래스 생성하여 적용하였습니다

2023-11-18 17:03 UTC, changgyu-kim commented on src/test/java/com/hwamok/notice/domain/NoticeTest.java
> +        String fakeContent = "내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내용내
ㄷㄷ.. 유틸클래스 생성하여 코드 이쁘게 정리했습니다

2023-11-18 17:10 UTC, LeeAYoung1207 approved these changes
고생하셨어요!

2023-11-19 06:09 UTC, goyounha11 commented on src/main/java/com/hwamok/notice/domain/Notice.java
> +  @Length(max = 1000)
validate메소드에서 할 수 있지 않나요?

2023-11-19 06:36 UTC, changgyu-kim commented on src/main/java/com/hwamok/notice/domain/Notice.java
> +  @Length(max = 1000)
DB에 바로 접근하여 입력할때도 1000자이상 입력이 안되도록 하려는 의도였습니다. 이건 신경 써도 되는걸까요??

2023-11-19 06:39 UTC, goyounha11 commented on src/main/java/com/hwamok/notice/domain/Notice.java
> +  @Length(max = 1000)
@changgyu-kim text로 줫다는 것 자체가 db에서 렝스관리 안한다는 겁니다.

2023-11-19 06:45 UTC, changgyu-kim commented on src/main/java/com/hwamok/notice/domain/Notice.java
> +  @Length(max = 1000)
아 그렇군요..  @Length 는 제거하고 validate메서드로 길이제한 적용하였습니다

2023-11-20 08:00 UTC, goyounha11 approved these changes

2023-11-20 16:05 UTC, GlenJeong approved these changes
고생했어요~

2023-11-20 16:13 UTC, merged