Hm 7 Category 도메인 개발
Hwamok/Hwamok-api-server pull request #15
Opened 2023-11-18 08:57 UTC by LeeAYoung1207

- 도메인 개발
- repository 테스트 추가
- Category Fixture 추가

2023-11-18 09:06 UTC, goyounha11 requested changes
@LeeAYoung1207 코멘트 확인하시고 수정해주세요.

2023-11-18 09:06 UTC, goyounha11 commented on src/main/java/com/hwamok/category/domain/Category.java
> +
의미 없는 주석 빼주세요

2023-11-18 09:06 UTC, goyounha11 commented on src/main/java/com/hwamok/category/domain/Category.java
> +    //String으로 넣어서 validate로 숫자만 넣는것을 확인할지, 혹은 int로 할지...
추후에 개선하실 것을 까먹는 것을 대비해서 넣은 주석이라면 todo를 써주세요 
아니라면 삭제해주세요

2023-11-18 09:06 UTC, goyounha11 commented on src/main/java/com/hwamok/category/domain/CategoryRepository.java
> +    Boolean existsByBranchAndName (String branch, String name);
메서드 사이는 공백하기로 컨벤션 정하지 않았나요?

2023-11-18 09:06 UTC, goyounha11 commented on src/main/java/com/hwamok/core/exception/ExceptionCode.java
>      ;
의미 없는 공백 제거해주세요

2023-11-18 09:06 UTC, goyounha11 commented on src/test/java/com/hwamok/category/domain/CategoryTest.java
> +
여기서 카테고리의 코드 생성 전략이 CA로 시작하기로 정하셨다면 CA로 시작한할때의 방어로직이 필요할 것 같습니다.

2023-11-18 09:06 UTC, goyounha11 commented on src/test/java/com/hwamok/category/domain/CategoryTest.java
> +    parentCategory.getSubCategory().add(subCategory2);
인스턴스를 생성하는 것과 리스트에 추가하는 작업은 결이 다른 것 같습니다. 공백 넣어주세요.

2023-11-18 09:06 UTC, goyounha11 commented on src/test/java/com/hwamok/category/domain/CategoryTest.java
> +    Assertions.assertThatIllegalArgumentException().isThrownBy(() ->
스태틱 임포트 해주세요

2023-11-18 09:06 UTC, goyounha11 commented on src/test/java/com/hwamok/category/domain/CategoryTest.java
> +    Assertions.assertThatIllegalArgumentException().isThrownBy(() ->
값이 없는게 아니라 null 혹은 빈값 아닌가요?

2023-11-18 09:06 UTC, goyounha11 commented on src/test/java/com/hwamok/category/domain/CategoryTest.java
> +  }
이 코드를 입력받는 형태가 아닌 서버내부에서 자동생성 전략을 사용하면 어떨까 싶은데 검토해주세요

2023-11-18 17:02 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/category/domain/Category.java
> +
뺐어요!

2023-11-18 17:02 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/category/domain/Category.java
> +    //String으로 넣어서 validate로 숫자만 넣는것을 확인할지, 혹은 int로 할지...
뻈어요!

2023-11-18 17:03 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/category/domain/CategoryRepository.java
> +    Boolean existsByBranchAndName (String branch, String name);
변경했어요!

2023-11-18 17:03 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/core/exception/ExceptionCode.java
>      ;
뺐습니다!

2023-11-18 17:03 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/category/domain/CategoryTest.java
> +
이건 좀 고민해볼게요... 자동 증가랑 연결지어서 바꾸고 설계해보겠습니다!

2023-11-18 17:03 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/category/domain/CategoryTest.java
> +    parentCategory.getSubCategory().add(subCategory2);
완료했습니다!

2023-11-18 17:03 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/category/domain/CategoryTest.java
> +    Assertions.assertThatIllegalArgumentException().isThrownBy(() ->
했습니다!

2023-11-18 17:04 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/category/domain/CategoryTest.java
> +    Assertions.assertThatIllegalArgumentException().isThrownBy(() ->
변경했습니디ㅏ!

2023-11-18 17:04 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/category/domain/CategoryTest.java
> +  }
이것도 오늘은 너무 늦어서 다시 검토해볼게요!

2023-11-19 02:47 UTC, changgyu-kim approved these changes
고생하셨습니다!

2023-11-19 06:11 UTC, goyounha11 commented on src/test/java/com/hwamok/category/domain/CategoryTest.java
> +
이 피알에서 하실건가요 아니면 따로 피알을 만드실 건가요

2023-11-19 06:13 UTC, goyounha11 commented on src/test/java/com/hwamok/category/domain/CategoryTest.java
> +  }
이거도 자동생성전략이 개발되야 가능할거같네요 다음 피알에서할지 이 피알에서 하실지 답변 주세요

2023-11-19 11:01 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/category/domain/CategoryTest.java
> +
따로 피알 만들게요!

2023-11-19 11:02 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/category/domain/CategoryTest.java
> +  }
다음 피알로 해야할것같아요 깃이 뭔가 꼬여서 일단 합치고 다시 받던 해야할거같아요..

2023-11-19 12:46 UTC, LeeAYoung1207 commented
> 고생하셨습니다!

2023-11-20 08:01 UTC, goyounha11 approved these changes

2023-11-20 09:36 UTC, changgyu-kim approved these changes
수고하셨습니다~

2023-11-20 13:44 UTC, GlenJeong commented
수고하셨습니다.

2023-11-20 13:44 UTC, GlenJeong approved these changes

2023-11-20 14:01 UTC, merged