Hm 6 Product 도메인 개발
Hwamok/Hwamok-api-server pull request #16
Opened 2023-11-18 11:14 UTC by LeeAYoung1207

product 도매인 개발
- entity 개발
- repository 개발
- exceptionCode 추가
- test 개발

2023-11-18 11:19 UTC, goyounha11 requested changes

2023-11-18 11:19 UTC, goyounha11 commented on src/main/java/com/hwamok/product/domain/Product.java
> +  @Column(length = 6, nullable = false)
이건뭐죠?

2023-11-18 11:19 UTC, goyounha11 commented on src/main/java/com/hwamok/product/domain/Product.java
> +    this.productStatus = ProductStatus.INACTIVATED;
프로퍼티
생성자
함수
게터
형태로 사용하시죠

2023-11-18 11:23 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/domain/Product.java
> +    this.productStatus = ProductStatus.INACTIVATED;
변경했어요!

2023-11-18 11:24 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/domain/Product.java
> +  @Column(length = 6, nullable = false)
어.. 그 category에 남겨주신것처럼 이 코드도 자동생성으로 바꿔보려구요..
근데 공부좀 해봐야 할것같아서 일단 todo로 남겨놨습니다.

2023-11-18 11:28 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/domain/Product.java
> +  @Column(length = 6, nullable = false)
다시변경했습니다!

2023-11-18 11:47 UTC, goyounha11 approved these changes

2023-11-19 02:48 UTC, changgyu-kim commented on src/main/java/com/hwamok/product/domain/Product.java
> +    PreConditions.require(productStatus != null);
productStatus의 값은 변수에 이미 저장되있어서 검증은 필요 없을 거 같아요

2023-11-19 02:48 UTC, changgyu-kim commented on src/main/java/com/hwamok/product/domain/Product.java
> +    PreConditions.require(price != null);
Integer 값으로 숫자가아닌 다른값이 들어올 경우에도 필수 값 검증이 필요할 거 같아요. 예를들어 문자열이 들어올 경우 에러가 나올 수 있을듯 합니다

2023-11-20 15:16 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/domain/Product.java
> +    PreConditions.require(price != null);
애초에 Integer안에 숫자가 아닌 다른값은 들어갈 수 없어, 검증에대한 생각을 해보지 않았는데,
창규님 말을 듣고나니 사용자는 해당 price가 Integer인지 모르기때문에 충분히 있을법한 일이라고 생각이드네요.
다만, 정규식은 String만 검증가능한것 같아서
price를 Integer가 아닌 String으로 바꿔야할지, 아니면 별도의 검증 방법이 있는지 잘 모르겠네요.
구글링해봐도 Integer를 검증하는 방식은 없는것같아 고민됩니다.
좀더 찾아보고 수정하겠습니다!

2023-11-20 15:34 UTC, goyounha11 commented on src/main/java/com/hwamok/product/domain/Product.java
> +    PreConditions.require(price != null);
@LeeAYoung1207 인티저에 스트링이 올 경우 InputMismatchException 뜨지않나요?

2023-11-20 15:40 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/domain/Product.java
> +    PreConditions.require(price != null);
넵..! 맞아요! 근데 그럼 도메인에서는 검증이 불가능한것 아닌가요...? 예외를 잡아서 처리하려면...

2023-11-20 15:42 UTC, goyounha11 commented on src/main/java/com/hwamok/product/domain/Product.java
> +    PreConditions.require(price != null);
그런건 아직 안배우긴했지만 가능하니까 일단 넘어가시죠

2023-11-20 15:50 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/domain/Product.java
> +    PreConditions.require(price != null);
아하... 넵 감사합니다!

2023-11-20 16:54 UTC, GlenJeong commented on src/main/java/com/hwamok/product/domain/Product.java
> +  public void updateProduct(String name, String code, Integer price, Category category){
category){ 컨벤션 확인해주세요.

2023-11-20 16:54 UTC, GlenJeong commented on src/main/java/com/hwamok/product/domain/Product.java
> +  public void deleteProduct(){
deleteProduct(){ 컨벤션 확인해주세요.

2023-11-20 16:54 UTC, GlenJeong commented on src/test/java/com/hwamok/product/domain/ProductTest.java
> +    private void setup(){
setup(){ 컨벤션 확인 부탁 드려요

2023-11-21 15:36 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/domain/Product.java
> +    PreConditions.require(productStatus != null);
변경했습니다!

2023-11-21 15:36 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/domain/Product.java
> +  public void updateProduct(String name, String code, Integer price, Category category){
변경했습니다!

2023-11-21 15:36 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/domain/Product.java
> +  public void deleteProduct(){
변경했습니다!

2023-11-21 15:37 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/product/domain/ProductTest.java
> +    private void setup(){
변경했습니다!

2023-11-22 10:57 UTC, changgyu-kim approved these changes
수고하셨습니다!

2023-11-22 11:14 UTC, GlenJeong commented on src/main/java/com/hwamok/product/domain/Product.java
> +  public void updateProduct(String name, String code, Integer price, Category category){
수고하셨습니다.

2023-11-22 11:14 UTC, GlenJeong commented on src/test/java/com/hwamok/product/domain/ProductTest.java
> +    private void setup(){
수고하셨습니다.

2023-11-22 11:15 UTC, GlenJeong approved these changes

2023-11-22 14:32 UTC, merged