Hm 18 User Service 개발
Hwamok/Hwamok-api-server pull request #18
Opened 2023-11-19 05:39 UTC by GlenJeong

2023-11-19 06:18 UTC, goyounha11 requested changes

2023-11-19 06:18 UTC, goyounha11 commented on src/main/java/com/hwamok/user/service/UserService.java
> +                String originalFileName, String savedFileName, int post, String addr, String detailAddr);
주소는 임베디드 객체로 알고있는데 다 풀어서 넘기면 추후에 또 new Address 해줘야하는거 아닌가영?

2023-11-19 06:18 UTC, goyounha11 commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
> +
여기도 추후에 창규님이 만든 랜덤유틸로 바꿔주세요

2023-11-20 13:38 UTC, GlenJeong commented on src/main/java/com/hwamok/user/service/UserService.java
> +                String originalFileName, String savedFileName, int post, String addr, String detailAddr);
네 맞습니다. 제가 임베디드에 대한 이해도가 없어서 생긴 일 같습니다. 수정했습니다.

2023-11-20 13:38 UTC, GlenJeong commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
> +
네 추후에 수정하도록 하겠습니다.

2023-11-20 16:41 UTC, changgyu-kim commented on src/main/java/com/hwamok/user/service/UserServiceImpl.java
>          return user;
update와 return 문 사이 공백 필요합니다

2023-11-20 16:41 UTC, changgyu-kim commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
>                  .orElseThrow(()-> new HwamokException(ExceptionCode.NOT_FOUND_USER));
userRepository에 유저를 저장할때 user정보를 얻어오는데 userRepository.findById() 메서드로 유저 정보를 찾아오는건 불필요해 보입니다.

2023-11-20 16:41 UTC, changgyu-kim commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
>      }
User 객체생성할때 발생하는 email의 검증은 domain에서 이루어져야하지 않을까요?

2023-11-20 16:41 UTC, changgyu-kim commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
User 객체생성할때 발생하는 password의 검증은 domain에서 이루어져야하지 않을까요?

2023-11-20 16:41 UTC, changgyu-kim commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
> +                        "201"))));
위 코드는 Service 검증이 아니라 repository 검증입니다.

2023-11-20 16:41 UTC, changgyu-kim commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
>      }
위 코드는 Service 검증이 아니라 repository 검증입니다.

2023-11-20 16:41 UTC, changgyu-kim commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
>      }
User 객체생성할때 발생하는 name의 검증은 domain에서 이루어져야하지 않을까요?

2023-11-20 16:41 UTC, changgyu-kim commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
위 사항과 같습니다. 아래도 같은 사항들이 있습니다.

2023-11-21 03:25 UTC, goyounha11 approved these changes

2023-11-22 09:24 UTC, GlenJeong commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
네 맞습니다. 불필요한 테스트를 삭제했습니다.

2023-11-22 09:24 UTC, GlenJeong commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
>      }
네 맞습니다. 불필요한 테스트를 삭제했습니다.

2023-11-22 09:24 UTC, GlenJeong commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
>      }
네 맞습니다. 불필요한 테스트를 삭제했습니다.

2023-11-22 09:24 UTC, GlenJeong commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
> +                        "201"))));
네 맞습니다. 불필요한 테스트를 삭제했습니다.

2023-11-22 09:24 UTC, GlenJeong commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
네 맞습니다. 불필요한 테스트를 삭제했습니다.

2023-11-22 09:24 UTC, GlenJeong commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
>      }
네 맞습니다. 불필요한 테스트를 삭제했습니다.

2023-11-22 09:26 UTC, GlenJeong commented on src/main/java/com/hwamok/user/service/UserServiceImpl.java
>          return user;
수정했습니다.

2023-11-22 10:48 UTC, GlenJeong commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
>                  .orElseThrow(()-> new HwamokException(ExceptionCode.NOT_FOUND_USER));
네 맞네요 불필요한 부분은 삭제했습니다.

2023-11-22 11:03 UTC, changgyu-kim approved these changes
수고하셨습니다!

2023-11-23 00:36 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/user/service/UserService.java
> +    User create(String email, String password, String name, String birthDay, String phone, String platform,
함수안에 파라미터가 너무 많아서.. 이거 다른 방법이 없으려나요...?
저도 이런게 있어서 고민이라서..
진짜 아얘 따로 dto를 만들어서 컨트롤로에서 해당 dto로 받아서 서비스로 넘겨받을지, 아니면 중요한것끼리 묶어서 class를 만들어가지고 그걸 클래스안에 변수로 넣을지.. 여러 방법을 고민하고 있긴한데
어렵네요...

2023-11-23 00:36 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
> +
그 10글자 초과인데 11글자가 아니라 12글자에요! 최소한으로 조건을 넘기는 걸 테스트하라고 했으니까
11글자로 수정하는게 좋을것같아요!

2023-11-23 00:36 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
> +
얘도 15글자에요! 12글자로 바꾸시는게 더 좋을것 같아요!

2023-11-23 00:36 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
> +        String fakeName = "hwamokhwamokhwamokhwamok";
20글자 초과인데 21글자가 아니라 24글자에요! 최소한으로 조건을 넘기는 걸 테스트하라고 했으니까
21글자로 수정하는게 좋을것같아요!

2023-11-23 00:36 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
> +        String fakeEmail = "hwamokhwamokhwamokhwamokhwamokhwamokhwamokhwamokhwamokhwamokhwamok@test.com";
50글자를 훨씬 더 초과했네요.. 최소한으로 초과하는게 좋을것 같아요!

2023-11-23 00:37 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/user/service/UserService.java
> +    User create(String email, String password, String name, String birthDay, String phone, String platform,
왜 며칠째 그대론가 했더니... 또 pending 상태였네요 ㅋㅋ
좌송합니다..

2023-11-23 05:01 UTC, GlenJeong commented on src/main/java/com/hwamok/user/service/UserService.java
> +    User create(String email, String password, String name, String birthDay, String phone, String platform,
쩌로님이 임베디드 객체에 대한 지적을 해주셔서 지금은 임베디드 객체 타입으로 이미 수정했습니다. 비슷한 성격의 필드들이 있다면 하나의 클래스로 마들어서 임베디드  타입으로 변경하는 걸 고민해 보시게 좋을 것 같아요

2023-11-23 05:03 UTC, GlenJeong commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
> +
서비스는 비즈니스에 관련 테스트를 진행해야 하는 데....도메인에 가까운 테스트라 지금은 다 삭제했습니다. 도메인에서 확인하고 수정하겠습니다.

2023-11-23 05:03 UTC, GlenJeong commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
> +
도메인에서 확인하고 수정하겠습니다.

2023-11-23 05:03 UTC, GlenJeong commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
> +        String fakeName = "hwamokhwamokhwamokhwamok";
도메인에서 확인하고 수정하겠습니다.

2023-11-23 05:03 UTC, GlenJeong commented on src/test/java/com/hwamok/user/service/UserServiceImplTest.java
> +        String fakeEmail = "hwamokhwamokhwamokhwamokhwamokhwamokhwamokhwamokhwamokhwamokhwamok@test.com";
도메인에서 확인하고 수정하겠습니다.

2023-11-23 06:02 UTC, LeeAYoung1207 approved these changes

2023-11-23 06:20 UTC, merged