HM-17 NoticeContoller 개발
Hwamok/Hwamok-api-server pull request #20
Opened 2023-11-20 15:32 UTC by changgyu-kim

2023-11-20 15:50 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/api/NoticeController.java
> +    // TODO: 2023-11-20 Jwt 구현 후 @AuthenticationPrincipal을 통해 SecurityContextHolder에 저장된 HwamokAdmin을 받아올 예정
여기 공백이 두줄이에요!

2023-11-20 15:50 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/api/NoticeController.java
> +
저희 시큐리티 안쓰고 세션쓰는건가요...?
아직 구현이 안되어있어서 session으로 권한을 주신건가요???

2023-11-20 15:50 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/api/NoticeControllerTest.java
> +
실패하는 테스트는 필요없을까요?
코드값이나 메시지같은것도 실패하는 결과값을 확인해야 할것같아요!

2023-11-20 15:52 UTC, changgyu-kim commented on src/main/java/com/hwamok/api/NoticeController.java
> +
아직 시큐리티와 jwt가 구현이 안되어있어서 session으로 진행했습니다. 위에 todo로 주석달아놓았어요~

2023-11-20 15:58 UTC, changgyu-kim commented on src/test/java/com/hwamok/api/NoticeControllerTest.java
> +
실패의 경우에는 domain과 service의 테스트코드에서 검증이 되어서 따로 필요는 없다고 생각됩니다!
controller 테스트는 요청과 응답이 잘이루어지는지를 확인하는 테스트로 알고있습니다.

2023-11-20 16:00 UTC, changgyu-kim commented on src/main/java/com/hwamok/api/NoticeController.java
> +    // TODO: 2023-11-20 Jwt 구현 후 @AuthenticationPrincipal을 통해 SecurityContextHolder에 저장된 HwamokAdmin을 받아올 예정
수정했습니다!

2023-11-20 16:13 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/api/NoticeController.java
> +
아하 제가 놓쳤나보네요! 확인했습니다! 감사합니다.

2023-11-20 16:19 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/api/NoticeControllerTest.java
> +
그건 맞는데, 응답은 잘 들어오더라도, 예를들어서 ExceptionHandler에서 필수값 누락된경우, E001코드와 필수값 누락 메시지가 뜨도록 되어있잖아요.
그럼 해당하는 메시지가 뜨는지 확인해봐야 하지 않는지 싶어서요!

2023-11-21 03:27 UTC, goyounha11 commented on src/test/java/com/hwamok/api/NoticeControllerTest.java
> +
에러가 잘 응답 되는지는 확인해볼 필요가 있겠죠

2023-11-21 07:03 UTC, changgyu-kim commented on src/test/java/com/hwamok/api/NoticeControllerTest.java
> +
말씀해주신대로 생각해보니 에러응답도 의도한대로 잘 동작하는지 테스트할 필요가 있겠군요!

2023-11-22 16:51 UTC, changgyu-kim commented on src/test/java/com/hwamok/api/NoticeControllerTest.java
> +
에러응답 추가했습니다

2023-11-23 06:05 UTC, LeeAYoung1207 approved these changes
고생하셨습니다

2023-11-23 09:33 UTC, goyounha11 requested changes

2023-11-23 09:33 UTC, goyounha11 commented on src/test/java/com/hwamok/api/NoticeControllerTest.java
> +                .andDo(MockMvcResultHandlers.print())
print는 빼주시죠

2023-11-24 02:42 UTC, GlenJeong approved these changes
고생했어요~

2023-11-24 04:24 UTC, changgyu-kim commented on src/test/java/com/hwamok/api/NoticeControllerTest.java
> +                .andDo(MockMvcResultHandlers.print())
네 수정했습니다

2023-11-25 07:33 UTC, goyounha11 commented on src/main/java/com/hwamok/api/NoticeController.java
> +        Page<Notice> notices = noticeService.getNotices(keyword, filter, curPage, pageSize);
@changgyu-kim @PageableDefault였나 이 애노테이션을 써서 더 깔끔하게 구현해보시져!

2023-11-28 05:58 UTC, changgyu-kim commented on src/main/java/com/hwamok/api/NoticeController.java
> +        Page<Notice> notices = noticeService.getNotices(keyword, filter, curPage, pageSize);
네 사용해서 깔끔하게 작성해보았습니다!

2023-11-28 06:00 UTC, goyounha11 approved these changes

2023-11-28 08:38 UTC, merged