Hm 20 Category Service 구현
Hwamok/Hwamok-api-server pull request #22
Opened 2023-11-21 14:31 UTC by LeeAYoung1207

카테고리 서비스 구현하면서 
일부 카테고리 도메인 수정도 같이 진행되었습니다.
양이 많지 않고, 카테고리 브랜치가 머지되었어서... 여기에 같이 커밋했습니다. :(

2023-11-22 11:17 UTC, GlenJeong approved these changes
enum ExceptionCode 충돌 발생하는 거 제가 수정했습니다.

2023-11-22 12:08 UTC, changgyu-kim approved these changes
수고하셨습니다!

2023-11-23 09:31 UTC, goyounha11 requested changes

2023-11-23 09:31 UTC, goyounha11 commented on src/main/java/com/hwamok/category/service/CategoryServiceImpl.java
> +
여기도 지금 보니 네이밍을 다시 고민해보시는게 좋겠습니다.

categoryService.saveCategory.. 흠..

2023-11-23 11:29 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/category/service/CategoryServiceImpl.java
> +
create() 로 변경했는데 괜찮을까요?

2023-11-23 11:57 UTC, goyounha11 approved these changes

2023-11-23 15:56 UTC, merged