Hm 21 product 서비스 구현
Hwamok/Hwamok-api-server pull request #24
Opened 2023-11-21 16:07 UTC by LeeAYoung1207

2023-11-22 12:18 UTC, changgyu-kim commented on src/main/java/com/hwamok/product/service/ProductServiceImpl.java
> +        return productRepository.findAllByNameAndStatus(name, ProductStatus.ACTIVATED);
name 값이 입력되어 들어오는 걸까요? repository 리턴값의 검증이 필요할 것 같아요!

2023-11-22 12:18 UTC, changgyu-kim commented on src/main/java/com/hwamok/product/service/ProductServiceImpl.java
> +    }
update, delete 메서드 각각 컨벤션 확인해주세요!

2023-11-22 14:36 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/service/ProductServiceImpl.java
> +        return productRepository.findAllByNameAndStatus(name, ProductStatus.ACTIVATED);
저 findAllbyNameAndStatus의 검증을 말씀하시는 걸까요?
해당 검증은 product repository 테스트에서 완료했습니다!

2023-11-22 14:38 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/service/ProductServiceImpl.java
> +    }
아.. 줄바꿈 말씀하시는거죠? 수정했습니다!

2023-11-23 09:30 UTC, goyounha11 requested changes

2023-11-23 09:30 UTC, goyounha11 commented on src/main/java/com/hwamok/product/service/ProductService.java
> +    List<Product> getProductByName(String name);
products를 가져오는데 메소드이름은 단수네요. 그리고 되게 jpa스러운데 네이밍 좀 더 고민해보세요

2023-11-23 09:30 UTC, goyounha11 commented on src/main/java/com/hwamok/product/service/ProductService.java
> +    Product createProduct(String name, String code, Integer price, Category category);
여기도 네이밍 다시 고민해보시죠
ProductService.createProduct 뭔가 의미중복같네요

2023-11-23 09:30 UTC, goyounha11 commented on src/main/java/com/hwamok/product/service/ProductService.java
> +    void deleteProduct(Long id);
여기도 전부 다요

2023-11-23 09:30 UTC, goyounha11 commented on src/main/java/com/hwamok/product/service/ProductServiceImpl.java
> +    }
( new 사이에 공백있네요

2023-11-23 09:30 UTC, goyounha11 commented on src/test/java/com/hwamok/product/service/ProductServiceImplTest.java
> +
도메인 테스트에서 이미 한거 아닌가요?

2023-11-23 11:35 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/service/ProductService.java
> +    List<Product> getProductByName(String name);
product를 찾아오는게 여러개라서 이렇게 붙였었는데... 지금보내 매우 jpa메서드랑 느낌이 비슷하네요...
그냥 findByName, findByCode 이런식으로 붙이는게 좋을까요?

2023-11-23 11:38 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/service/ProductService.java
> +    Product createProduct(String name, String code, Integer price, Category category);
create로변경했어요!

2023-11-23 11:38 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/service/ProductService.java
> +    void deleteProduct(Long id);
delete로 변경했어요

2023-11-23 11:39 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/service/ProductServiceImpl.java
> +    }
제거했습니다!

2023-11-23 11:40 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/product/service/ProductServiceImplTest.java
> +
이게 항상 헷깔리네요...
도메인에서 전부 다진행한거긴 한데, 서비스에서 제가 원한값과 에러코드가 잘 나오는지 확인해야 할것 같아서 전부쓰긴 했거든요.
어느정도 선으로 작성하는게 제일 좋을까요??

2023-11-23 11:52 UTC, goyounha11 commented on src/test/java/com/hwamok/product/service/ProductServiceImplTest.java
> +
음.. 그런 이유라면 작성하셔도 무방할 것 같습니다. 서비스에서도 실제로 나오는지 궁금했다가 이유가 될 수 있죠
이게 쌓이면 이제 도메인 코드를 신뢰하게되고 서비스에서는 이 코드를 쓰는게 의미없게 느껴질 때가 올 수 있습니다.
그때 안하시면되졍 ㅎ

그리고 랜덤유틸있는거로 아는데 그거 사용해주시죠

2023-11-23 11:52 UTC, LeeAYoung1207 commented on src/test/java/com/hwamok/product/service/ProductServiceImplTest.java
> +
아하... 넵! 감사합니다 수정하겠습니다!

2023-11-23 11:56 UTC, goyounha11 requested changes

2023-11-23 11:56 UTC, goyounha11 commented on src/main/java/com/hwamok/product/service/ProductService.java
> +    List<Product> getProductByName(String name);
서비스의 비지니스 로직은 그저 프로덕트를 가져온다 아닌가요?

2023-11-24 03:07 UTC, GlenJeong approved these changes

2023-11-24 03:30 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/product/service/ProductService.java
> +    List<Product> getProductByName(String name);
맞긴한데, getproduct가 두종류라서요, code로 가져오는게 있고, name으로 가져오는게 있는데 오버로딩으로 쓰기에는 둘다 매개변수가 String 하나라서... 어떤식으로 해야할지 감이 안잡히네요
다른 좋은 방식이 있을까요?

2023-11-24 04:36 UTC, changgyu-kim approved these changes
수고하셧습니다!

2023-11-25 07:36 UTC, goyounha11 commented on src/main/java/com/hwamok/product/service/ProductService.java
> +    List<Product> getProductByName(String name);
좀 애매하긴하네요. 일단 리졸브하고 고민을 좀 해보죵

2023-11-25 07:37 UTC, goyounha11 approved these changes

2023-12-02 04:48 UTC, merged