Hm 29 Jwt 토큰생성, 유저, 관리자로그인 개발
Hwamok/Hwamok-api-server pull request #33
Opened 2023-12-01 10:17 UTC by changgyu-kim

2023-12-02 04:52 UTC, LeeAYoung1207 approved these changes
고생하셨습니다.

2023-12-04 01:21 UTC, goyounha11 requested changes

2023-12-04 01:21 UTC, goyounha11 commented on src/main/java/com/hwamok/api/AuthController.java
> +
userLogin -> login어떤가요?

2023-12-04 01:21 UTC, goyounha11 commented on src/main/java/com/hwamok/auth/service/AuthService.java
> +    Pair<String, String> adminLogin(String loginId, String password);
AuthService에 퉁치는게아니라 UserAuthService, AdminAuthService 분리되는게 맞지않을까요?

2023-12-04 01:21 UTC, goyounha11 commented on src/main/java/com/hwamok/auth/service/AuthServiceImpl.java
> +        String refreshToken = jwtService.issue(admin.getId(), role, JwtType.REFRESH);
Role을 넣어주는게아닌 RoleId가 들어가는게 안전해보이는데 어떤가요?

2023-12-04 01:21 UTC, goyounha11 commented on src/test/java/com/hwamok/api/AuthControllerTest.java
> +
문서화는 안하나요?

2023-12-04 01:21 UTC, goyounha11 commented on src/test/java/com/hwamok/auth/service/AuthServiceImplTest.java
> +        Assertions.assertThat(pair.getSecond()).isEqualTo(jwtService.issue(user.getId(), user.getRole().getName(), JwtType.REFRESH));
스태틱 임포트 해주세요

2023-12-04 04:57 UTC, changgyu-kim commented on src/test/java/com/hwamok/auth/service/AuthServiceImplTest.java
> +        Assertions.assertThat(pair.getSecond()).isEqualTo(jwtService.issue(user.getId(), user.getRole().getName(), JwtType.REFRESH));
네 수정했습니다

2023-12-04 04:57 UTC, changgyu-kim commented on src/main/java/com/hwamok/api/AuthController.java
> +
네 수정했습니다

2023-12-04 04:57 UTC, changgyu-kim commented on src/main/java/com/hwamok/auth/service/AuthService.java
> +    Pair<String, String> adminLogin(String loginId, String password);
그렇네요.. User 와 Admin 분리했습니다

2023-12-04 05:02 UTC, goyounha11 requested changes

2023-12-04 05:02 UTC, goyounha11 commented on src/main/java/com/hwamok/api/UserAuthController.java
> +        return Result.ok(new UserLoginDto.Response(pair.getFirst(), pair.getSecond()));
UserAuth인 것을 이미 인지하고 있는데 userLogin보다는 login이 나은거같습니다

2023-12-04 05:02 UTC, changgyu-kim commented on src/main/java/com/hwamok/auth/service/AuthServiceImpl.java
> +        String refreshToken = jwtService.issue(admin.getId(), role, JwtType.REFRESH);
Role 이넘클래스에서 각 역할에 대한 RoleId를 추가하고 그 RoleId를 넣어준다는걸로 이해했는데 맞는걸까요?

2023-12-04 05:05 UTC, goyounha11 commented on src/main/java/com/hwamok/auth/service/AuthServiceImpl.java
> +        String refreshToken = jwtService.issue(admin.getId(), role, JwtType.REFRESH);
아 엘리멘탈 컬렉션으로 했었지. 순간 착각했네요. 그럼 이건 패스해도될 것 같고 아래 내용 검토 해주세요.
어드민 권한을 SUPER, ADMIN 둘다 가지고있을 경우는 어떻게할 수 잇을까요?

2023-12-04 05:07 UTC, changgyu-kim commented on src/main/java/com/hwamok/auth/service/AuthServiceImpl.java
> +        String refreshToken = jwtService.issue(admin.getId(), role, JwtType.REFRESH);
어드민 권한을 둘다 가지고있을 경우에는 SUPER 가 상위역할이여서 SUPER 역할만 가질 수 있도록 했습니다. 이럴경우 문제가 생길수 있을까요??

2023-12-04 05:09 UTC, goyounha11 commented on src/main/java/com/hwamok/auth/service/AuthServiceImpl.java
> +        String refreshToken = jwtService.issue(admin.getId(), role, JwtType.REFRESH);
그러기엔 생성할때도 리스트로 들어가는데 어떻게 제어할 생각이신가요??

2023-12-04 06:56 UTC, changgyu-kim commented on src/main/java/com/hwamok/api/UserAuthController.java
> +        return Result.ok(new UserLoginDto.Response(pair.getFirst(), pair.getSecond()));
네 UserAuth, AdminAuth 둘다 login 으로 변경했습니다

2023-12-04 07:01 UTC, changgyu-kim commented on src/main/java/com/hwamok/auth/service/AuthServiceImpl.java
> +        String refreshToken = jwtService.issue(admin.getId(), role, JwtType.REFRESH);
말씀하신 생성할때가 토큰생성하는것 말씀이실까요? 현재로직에서는 role 리스트에 SUPER가 있을경우에 String으로 SUPER를 저장하고 없을경우 ADMIN을 토큰에 저장하는 방식으로 했습니다

2023-12-04 08:45 UTC, changgyu-kim commented on src/test/java/com/hwamok/api/AuthControllerTest.java
> +
문서화 작성했습니다.  같은 tag를 가진 문서 안에서 schema 변화가 없는 문제가 있습니다.

2023-12-05 02:27 UTC, goyounha11 commented on src/main/java/com/hwamok/auth/service/AuthServiceImpl.java
> +        String refreshToken = jwtService.issue(admin.getId(), role, JwtType.REFRESH);
A유저가 2개의 권한을 가지고 있을 경우에 오류는 없을까요?

2023-12-06 00:59 UTC, changgyu-kim commented on src/main/java/com/hwamok/auth/service/AuthServiceImpl.java
> +        String refreshToken = jwtService.issue(admin.getId(), role, JwtType.REFRESH);
```
@Enumerated(EnumType.STRING)
  private Role role = Role.USER;
```
현재 유저는 도메인생성 시  이렇게 하나의 권한을 가지도록 되어있어서 오류는 없는데 유저가 여러권한을 가지게 될경우에는 오류가 납니다
혹시 유저가 권한을 여러개 가질 필요가 있을까요?? 유저가 권한이 여러개 가지면 Admin과 User의 도메인을 나누지 않고 Role로 역할구분하여 하나로 두는게 더 관리하기 편할거 같다는 생각도 드네요..

2023-12-06 01:02 UTC, goyounha11 commented on src/main/java/com/hwamok/auth/service/AuthServiceImpl.java
> +        String refreshToken = jwtService.issue(admin.getId(), role, JwtType.REFRESH);
유저는 단일 권한으로 가는 것으로 하더라도 어드민은용?

2023-12-06 01:09 UTC, changgyu-kim commented on src/main/java/com/hwamok/auth/service/AuthServiceImpl.java
> +        String refreshToken = jwtService.issue(admin.getId(), role, JwtType.REFRESH);
2개 이상의 권한을 가지고 있을 경우
더 높은 권한으로 토큰을 생성하게 하였습니다

2023-12-06 01:16 UTC, goyounha11 commented on src/main/java/com/hwamok/auth/service/AuthServiceImpl.java
> +        String refreshToken = jwtService.issue(admin.getId(), role, JwtType.REFRESH);
권한이 세부적으로 추가되면 이 로직도 변경되어야하나요?

2023-12-06 01:39 UTC, changgyu-kim commented on src/main/java/com/hwamok/auth/service/AuthServiceImpl.java
> +        String refreshToken = jwtService.issue(admin.getId(), role, JwtType.REFRESH);
네 다른 권한이 추가되면 if문 하나가 추가됩니다

2023-12-06 12:45 UTC, GlenJeong approved these changes

2023-12-07 01:07 UTC, goyounha11 commented on src/main/java/com/hwamok/auth/service/AuthServiceImpl.java
> +        String refreshToken = jwtService.issue(admin.getId(), role, JwtType.REFRESH);
흠.. 별로 좋은 방식은 아닌거같은데.. 추후 리팩토링으로 잡아두죠

2023-12-07 01:07 UTC, goyounha11 approved these changes

2023-12-07 08:51 UTC, merged