Hm 37 Category Repository 메서드 수정
Hwamok/Hwamok-api-server pull request #34
Opened 2023-12-02 07:13 UTC by LeeAYoung1207

메서드 수정이 필요해서 메서드 한개를 수정했고,
이에따라 service와 테스트를 수정했습니다.

2023-12-03 05:20 UTC, GlenJeong approved these changes

2023-12-03 05:56 UTC, changgyu-kim commented on src/main/java/com/hwamok/category/service/CategoryServiceImpl.java
> +
Optional<Category> findByIdAndStatus (Long, CategoryStatus status); 를 활용하면 if문을 사용하지않고 코드가 더 깔끔해지지 않을까요..?
delete 함수도 해당됩니다!

2023-12-03 08:54 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/category/service/CategoryServiceImpl.java
> +
음.. 삭제된 것을 불러왔을때 없으면 에러가 날까 싶어서 일부러 저렇게 구현한거긴한데,
생각해보니 삭제된걸 불러온다는 것 자체가 이상하겠네요.
수정했습니다.

2023-12-03 16:58 UTC, changgyu-kim approved these changes

2023-12-04 01:39 UTC, goyounha11 requested changes

2023-12-04 01:39 UTC, goyounha11 commented on src/main/java/com/hwamok/category/service/CategoryServiceImpl.java
>              }
create 메소드의 비지니스 로직이 잘 이해가 안가는데 플로우 설명 부탁드립니다.

2023-12-04 05:21 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/category/service/CategoryServiceImpl.java
>              }
1. 카테고리를 생성하기 위한 카테고리를 선언
2. 등록을 희망하는 parentCategory있는지 판별

3.. 등록 희망하는 parent 없으면, 루트카테고리 찾기 (없으면 생성) 후 추가>> 루트카테고리 등록
4. 카테고리에 branch, code, name, rootCategory 넣어서 카테고리 생성, 이때 레벨은 1로 등록

5. 등록 희망하는 parent 있으면, 해당 카테고리를 Id값으로 찾아와서 parentCategory를 추가
6. 카테고리에 branch, code, name, rootCategory 넣어서 카테고리 생성, 이때 레벨은 원 부모카테고리 레벨의 +1값으로 등록
7. parent아래에 자식카테고리로 지금 만드는 카테고리 추가

8. DB에 저장

이정도면 될까요?

2023-12-04 05:30 UTC, goyounha11 commented on src/main/java/com/hwamok/category/service/CategoryServiceImpl.java
>              }
음.. 그럼 코드 개선이 좀 필요하겠네요
어떻게 하면 더 좋은 코드를 작성할 수 있을지 고민 한번 해보시졍!

2023-12-04 05:36 UTC, goyounha11 commented on src/main/java/com/hwamok/category/service/CategoryServiceImpl.java
>              }
루트카테고리와 패런트카테고리는 틀린건가요?

2023-12-04 08:37 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/category/service/CategoryServiceImpl.java
>              }
네 root는 제일 맨위의 (각 브랜치별 카테고리의 기본이되는) 카테고리고, 부모카테고리는 지금 만드는 카테고리의 바로 위에 있는 카테고리에요!

 root-식품-과자-초코과자
 ------------------옛날과자
------------고기-돼지고기
 ------------------소고기

이런식인데 고기는 소고기의 parent고 root는 최상단 인거죠

2023-12-07 01:06 UTC, goyounha11 approved these changes

2023-12-07 11:53 UTC, merged