HM-36 SpringSecurity 개발, test코드 @WithUserDetails 추가
Hwamok/Hwamok-api-server pull request #37
Opened 2023-12-04 16:07 UTC by changgyu-kim

부족한 부분이나 이상한 부분이 있다면 피드백 요청드립니다.

2023-12-05 02:31 UTC, goyounha11 requested changes

2023-12-05 02:31 UTC, goyounha11 commented on src/main/generated/com/hwamok/category/domain/QCategory.java
>      public final StringPath name = createString("name");
Qclass는 gitignore에 등록해주세요.

2023-12-05 02:31 UTC, goyounha11 commented on src/main/java/com/hwamok/api/NoticeController.java
> +        noticeService.create(request.getTitle(), request.getContent(), hwamokAdmin.getId());
hwamokAdmin.getId(); 이거는 어디에 사용되나요?

2023-12-05 02:31 UTC, goyounha11 commented on src/main/java/com/hwamok/config/SecurityConfig.java
> +                        request.requestMatchers(HttpMethod.DELETE, "/notice/**", "/admin/**").hasAnyAuthority("어드민", "슈퍼 어드민"))
Enum으로 해야하지 않나요?

2023-12-05 02:31 UTC, goyounha11 commented on src/main/java/com/hwamok/security/authenticationProvider/DefaultAuthenticationProvider.java
> +        }
이넘으로해주세요

2023-12-05 02:31 UTC, goyounha11 commented on src/main/java/com/hwamok/security/jwt/JwtTokenFilter.java
> +            UsernamePasswordAuthenticationToken usernamePasswordAuthenticationToken =
여기도 이넘으로 해주세여

2023-12-05 02:31 UTC, goyounha11 commented on src/main/java/com/hwamok/security/userDetails/HwamokAdmin.java
> +
이넘으로해주세요

2023-12-06 01:46 UTC, changgyu-kim commented on src/main/java/com/hwamok/security/jwt/JwtTokenFilter.java
> +            UsernamePasswordAuthenticationToken usernamePasswordAuthenticationToken =
어느부분을 이넘으로 하라는 말씀이실까요??

2023-12-06 01:49 UTC, changgyu-kim commented on src/main/java/com/hwamok/security/userDetails/HwamokAdmin.java
> +
제가 토큰만들때 String값을 토큰에 담도록 하고있는데 그래도 이넘으로 바꾸어야 할까요?

2023-12-06 01:53 UTC, changgyu-kim commented on src/main/java/com/hwamok/config/SecurityConfig.java
> +                        request.requestMatchers(HttpMethod.DELETE, "/notice/**", "/admin/**").hasAnyAuthority("어드민", "슈퍼 어드민"))
```
.authorizeHttpRequests(request ->
                        request.requestMatchers(HttpMethod.GET, API_NOTICE).hasAnyAuthority(Role.ADMIN.getName(), Role.SUPER.getName()))
```
이런식으로 하라는 말씀이실까요?

2023-12-06 04:48 UTC, changgyu-kim commented on src/main/generated/com/hwamok/category/domain/QCategory.java
>      public final StringPath name = createString("name");
네 등록했습니다.

2023-12-06 04:48 UTC, changgyu-kim commented on src/main/java/com/hwamok/api/NoticeController.java
> +        noticeService.create(request.getTitle(), request.getContent(), hwamokAdmin.getId());
불필요한 코드입니다 삭제했습니다.

2023-12-06 04:48 UTC, changgyu-kim commented on src/main/java/com/hwamok/security/authenticationProvider/DefaultAuthenticationProvider.java
> +        }
네 수정했습니다.

2023-12-07 01:08 UTC, goyounha11 commented on src/main/java/com/hwamok/config/SecurityConfig.java
> +                        request.requestMatchers(HttpMethod.DELETE, "/notice/**", "/admin/**").hasAnyAuthority("어드민", "슈퍼 어드민"))
흠... Authority관련해서는 머지 후에 제가 pr로 오픈하겠습니다.

2023-12-07 01:09 UTC, goyounha11 approved these changes
권한 관련해서는 일단 머지하고 제가 추후에 리팩토링 후 pr열겠습니다.

2023-12-07 11:06 UTC, GlenJeong approved these changes

2023-12-07 11:53 UTC, LeeAYoung1207 approved these changes

2023-12-07 11:54 UTC, merged