Hm 27 - Category Controller
Hwamok/Hwamok-api-server pull request #43
Opened 2023-12-11 16:00 UTC by LeeAYoung1207

ExceptionCode 수정해서 다시올려요!

2023-12-13 02:30 UTC, goyounha11 requested changes

2023-12-13 02:30 UTC, goyounha11 commented on src/main/java/com/hwamok/api/CategoryController.java
> +                .build();
빌더 패턴 말고 응답객체안에 생성자를 넣어서 해주세요

2023-12-13 02:30 UTC, goyounha11 commented on src/main/java/com/hwamok/api/CategoryController.java
> +                category.getName(), category.getLevel() , category.getParentId());
이거도 Category를 인자로 받아서 응답객체 내부에서 매핑 작업해주세요.

2023-12-13 02:30 UTC, goyounha11 commented on src/main/java/com/hwamok/api/dto/category/CategoryReadDTO.java
> +    @Builder
Builder안쓰면 빼주세요

2023-12-13 02:30 UTC, goyounha11 commented on src/main/java/com/hwamok/category/domain/Category.java
> +  @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
PERSIST는 왜 한 것인가요?

2023-12-13 02:30 UTC, goyounha11 commented on src/main/java/com/hwamok/category/domain/Category.java
> +    return null;
if문 없으면 에러나나요?

2023-12-13 04:09 UTC, changgyu-kim commented on src/main/java/com/hwamok/api/dto/category/CategoryCreateDTO.java
> +public class CategoryCreateDTO {
DTO를 Dto로 기존에 작성된 것들과 같이표기법을 통일하는게 좋을거 같아요!

2023-12-14 01:53 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/api/CategoryController.java
> +                .build();
네 수정하겠습니다. 요새 회사가 연말이라 정신이없네요..ㅠㅠ

2023-12-14 01:55 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/category/domain/Category.java
> +  @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
이게 없이 하다보니 중간에 생성할때 문제가 생기더라구요, 찾아보니까 부모가 생기면서 자식이 영속성등록이 안되어가지고 생기는 생성오류라고 하던데, cacade.persist가 해당 요소까지 영속성객체로 등록해준다고 추가하면 된다길래 추가했습니다.

2023-12-14 01:58 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/category/domain/Category.java
> +    return null;
어..에러나는지는 테스트틑 해보지 않았는데요, 로직 설계할때, category가 null이면 id 가져올필요가 없으니까 해당 if문을 넣었던건데 의미가 없을까요?

2023-12-14 01:58 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/api/dto/category/CategoryCreateDTO.java
> +public class CategoryCreateDTO {
앗 네! 오늘밤에 수정하겠습니다! 감사합니다!

2023-12-14 02:36 UTC, goyounha11 commented on src/main/java/com/hwamok/category/domain/Category.java
> +    return null;
그러면 삼항연산자가 더 깔끔해보이네요

2023-12-14 10:20 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/category/domain/Category.java
> +    return null;
아하 넵! 수정하겠습니다!

2023-12-14 11:45 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/api/CategoryController.java
> +                .build();
수정했습니다

2023-12-14 11:45 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/api/CategoryController.java
> +                category.getName(), category.getLevel() , category.getParentId());
수정했습니다

2023-12-14 11:45 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/api/dto/category/CategoryReadDTO.java
> +    @Builder
수정했습니다

2023-12-14 11:46 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/category/domain/Category.java
> +    return null;
수정했습니다

2023-12-14 11:46 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/api/dto/category/CategoryCreateDTO.java
> +public class CategoryCreateDTO {
수정했습니다

2023-12-16 14:05 UTC, goyounha11 requested changes

2023-12-16 14:05 UTC, goyounha11 commented on src/main/java/com/hwamok/category/domain/Category.java
> +    return parentCategory != null? parentCategory.getId() : null;
parentCategory != null ? 띄어쓰기해주세요

2023-12-17 03:57 UTC, LeeAYoung1207 commented on src/main/java/com/hwamok/category/domain/Category.java
> +    return parentCategory != null? parentCategory.getId() : null;
수정했습니다!

2023-12-19 01:27 UTC, goyounha11 approved these changes

2023-12-19 01:43 UTC, GlenJeong approved these changes

2023-12-20 10:31 UTC, changgyu-kim approved these changes

2023-12-20 10:45 UTC, merged