Hm 8 User 도메인 개발
Hwamok/Hwamok-api-server pull request #8
Opened 2023-11-16 15:37 UTC by GlenJeong

2023-11-17 03:09 UTC, goyounha11 commented
디벨롭 풀 받고 다시 PR오픈해주세요 다 컨플릭트 나고 있네요

2023-11-17 05:46 UTC, GlenJeong commented
충돌 완료 했습니다.

2023-11-17 09:16 UTC, goyounha11 commented
@GlenJeong 공백 컨벤션에 대한 부분 다시 검토 후 멘션주세요

2023-11-17 11:35 UTC, GlenJeong commented
User 도메인 불필요한 공백 삭제하고 줄 정렬 및 공백 컨벤션 했습니다.

2023-11-17 11:37 UTC, GlenJeong commented
Develop에서 내려 받고 난 후 일부 코드 오류 난 거 정리 
	공통 소스와 중복 된 부분 중 내 소스에서 삭제 
	core -> preconditions 삭제
	util -> RegexType, RegexUtil 삭제
	config -> SecurityConfiguration 삭제 
	testFixtures -> userFixture -> fixture 패키지로 이동
-----------------------------------------------------------------

User 도메인 불필요한 공백 삭제 및 줄 정렬, 공백 컨벤션
	              날짜 validate 추가 및 사용하지 않는 코드 삭제
UserTest 회원 가입, 회원 수정, 회원 탈퇴 테스트 코드 진행

-----------------------------------------------------------------

utils
RegexType -> birthDay 추가
RegexUtil -> 날짜 정규식 추가

core -> exception -> ExceptionCode -> NOT_FOUND_USER, NOT_DATE_FORM 추가


Develop에서 pull하고 난 뒤 현재까지 작업 내역 간단히 올립니다.

2023-11-18 09:54 UTC, goyounha11 requested changes
@GlenJeong 공백 컨벤션 확인 다시 해주세요

2023-11-18 09:54 UTC, goyounha11 commented on src/main/java/com/hwamok/api/UserController.java
> +        userService.create(
해당 메소드가 회원가입이라는 것을 명시하고 싶다면 JAVA doc을 써주세요

2023-11-18 09:54 UTC, goyounha11 commented on src/main/java/com/hwamok/api/UserController.java
> +        return Result.ok(user);
탈퇴한 유저를 반환해주는 이유가 있나요?

2023-11-18 09:54 UTC, goyounha11 commented on src/main/java/com/hwamok/api/dto/AddressCreateDto.java
> +}
공백 컨벤션 지켜주세요.

2023-11-18 09:54 UTC, goyounha11 commented on src/main/java/com/hwamok/api/dto/AddressUpdateDto.java
> +}
여기도요

2023-11-18 09:54 UTC, goyounha11 commented on src/main/java/com/hwamok/api/dto/UploadedFileCreateDto.java
> +}
여기도요

2023-11-18 09:54 UTC, goyounha11 commented on src/main/java/com/hwamok/api/dto/UploadedFileUpdateDto.java
> +}
여기도요

2023-11-18 11:54 UTC, GlenJeong commented on src/main/java/com/hwamok/api/UserController.java
> +        userService.create(
불필요한 주석 삭제 했습니다.

2023-11-18 11:55 UTC, GlenJeong commented on src/main/java/com/hwamok/api/UserController.java
> +        return Result.ok(user);
아니요  삭제했습니다.

2023-11-18 11:55 UTC, GlenJeong commented on src/main/java/com/hwamok/api/dto/AddressCreateDto.java
> +}
네 컨벤션 적용했습니다.

2023-11-18 11:55 UTC, GlenJeong commented on src/main/java/com/hwamok/api/dto/AddressUpdateDto.java
> +}
적용했습니다.

2023-11-18 11:56 UTC, GlenJeong commented on src/main/java/com/hwamok/api/dto/UploadedFileCreateDto.java
> +}
적용했습니다

2023-11-18 11:56 UTC, GlenJeong commented on src/main/java/com/hwamok/api/dto/UploadedFileUpdateDto.java
> +}
적용했습니다

2023-11-18 11:58 UTC, goyounha11 requested changes

2023-11-18 11:58 UTC, goyounha11 commented on src/main/java/com/hwamok/core/exception/ExceptionCode.java
>      ;
공백제거해주세요

2023-11-18 11:58 UTC, goyounha11 commented on src/main/java/com/hwamok/user/service/UserServiceImpl.java
>          User user = userRepository.findById(id).orElseThrow(() -> new RuntimeException("NOT_FOUND_USER"));
유저가 탈퇴하는 행위는 WIthdraw가 어울리지않나요?
바꾸신 이유가 뭘까영

2023-11-18 12:02 UTC, GlenJeong commented on src/main/java/com/hwamok/user/service/UserServiceImpl.java
>          User user = userRepository.findById(id).orElseThrow(() -> new RuntimeException("NOT_FOUND_USER"));
withdraw보다 delete 의미가 더 명확하게 전달 되는 것 같아서 변경했습니다. 다시 바꿀까요?

2023-11-18 12:03 UTC, GlenJeong commented on src/main/java/com/hwamok/core/exception/ExceptionCode.java
>      ;
네 알겠습니다.

2023-11-19 02:44 UTC, changgyu-kim commented on src/main/java/com/hwamok/api/UserController.java
> +
저희 컨벤션은 클래스아래 공백없이 코드를 작성해가기로 했었습니다.  다른곳도 붙여서 작성해주세요

2023-11-19 02:44 UTC, changgyu-kim commented on src/main/java/com/hwamok/api/dto/user/AddressCreateDto.java
> +
여기도 붙여야 합니다

2023-11-19 02:44 UTC, changgyu-kim commented on src/main/java/com/hwamok/user/domain/Address.java
>    private String detailAddr;
주소와 상세주소 length 설정도 필요하지 않을까요?

2023-11-19 02:44 UTC, changgyu-kim commented on src/main/java/com/hwamok/user/domain/JoinPlatform.java
> +  GOOGLE("Goo1", "구글 회원");
기존에 작성했던 코드에서 code와 message를 추가한 이유가 있을까요? 다른곳에서 사용되어지지는 않는 것 같습니다

2023-11-19 02:44 UTC, changgyu-kim commented on src/test/java/com/hwamok/user/domain/UserTest.java
> +    // 3. 결이 다를 때
불필요한 주석입니다

2023-11-19 02:44 UTC, changgyu-kim commented on src/test/java/com/hwamok/user/domain/UserTest.java
> +
회원탈퇴 메서드는 user의 status만 변경되는데 이것만 테스트 해보면 되지 않을까요?

2023-11-19 02:44 UTC, changgyu-kim commented on src/test/java/com/hwamok/user/domain/UserTest.java
> +
email은 50글자까지 작성가능한걸로 구현하였는데 실패사유를 50글자 초과로 쓰셔야 할 거 같습니다. 다른 코드도 비슷한 점이 있으면 수정해주세요

2023-11-19 02:44 UTC, changgyu-kim commented on src/main/java/com/hwamok/user/service/UserServiceImpl.java
> +
여기도 공백 삭제해주세요

2023-11-19 02:44 UTC, changgyu-kim commented on src/main/java/com/hwamok/user/service/UserServiceImpl.java
> +    }
user객체가 다른로직을 수행 안하는것 같은데 따로 값을 받아서 리턴하지 말고 바로값을 리턴해주면 코드가 더 깔끔할 것 같습니다. 비슷한 다른코드도 해당됩니다.

2023-11-19 02:44 UTC, changgyu-kim commented on src/main/java/com/hwamok/user/service/UserServiceImpl.java
> +        userRepository.save(user);
@Transaction 에노테이션이 있으므로 세이브할 필요는 없어보입니다.

2023-11-19 02:44 UTC, changgyu-kim commented on src/main/java/com/hwamok/api/UserController.java
> +    @PatchMapping("/update/{id}")
@PatchMapping에 update의미가 있는데 api에 update를 사용하는것은 불필요해 보입니다

2023-11-19 02:44 UTC, changgyu-kim commented on src/main/java/com/hwamok/api/UserController.java
> +    @DeleteMapping ("/delete/{id}")
@DeleteMapping에 delete의미가 있는데 api 에 delete를 사용하는것은 불필요해 보입니다

2023-11-19 02:53 UTC, GlenJeong commented on src/main/java/com/hwamok/user/domain/Address.java
>    private String detailAddr;
네 필요해 보이네요~ 최대 주소 길이를 예측해 보고 설정해 보도록 하겠습니다.

2023-11-19 02:53 UTC, GlenJeong commented on src/main/java/com/hwamok/user/domain/JoinPlatform.java
> +  GOOGLE("Goo1", "구글 회원");
필요하지 않을 까 싶어서 작성했는 데 현재까지는 쓸 일이 없는 듯 해요 불필요한 코드로 보이니 지웠다가 필요한 시점이 생기면 추가할게요~

2023-11-19 02:54 UTC, GlenJeong commented on src/test/java/com/hwamok/user/domain/UserTest.java
> +    // 3. 결이 다를 때
네~ 지울게요

2023-11-19 04:30 UTC, GlenJeong commented on src/main/java/com/hwamok/api/UserController.java
> +
네 수정했습니다.

2023-11-19 04:30 UTC, GlenJeong commented on src/main/java/com/hwamok/api/dto/user/AddressCreateDto.java
> +
네 수정했습니다.

2023-11-19 04:31 UTC, GlenJeong commented on src/main/java/com/hwamok/user/domain/Address.java
>    private String detailAddr;
네 의견 수렴하여 주소와 상세주소 length 설정해서 수정했습니다.

2023-11-19 04:31 UTC, GlenJeong commented on src/main/java/com/hwamok/user/domain/JoinPlatform.java
> +  GOOGLE("Goo1", "구글 회원");
네 의미없는 코드 삭제 후 수정했습니다.

2023-11-19 04:31 UTC, GlenJeong commented on src/test/java/com/hwamok/user/domain/UserTest.java
> +    // 3. 결이 다를 때
의미 없는 주석 삭제했습니다.

2023-11-19 04:32 UTC, GlenJeong commented on src/test/java/com/hwamok/user/domain/UserTest.java
> +
네 맞네요 수정했습니다

2023-11-19 04:32 UTC, GlenJeong commented on src/test/java/com/hwamok/user/domain/UserTest.java
> +
네 맞네요 의견 수렴했습니다

2023-11-19 04:32 UTC, GlenJeong commented on src/main/java/com/hwamok/user/service/UserServiceImpl.java
> +
네 삭제 했습니다.

2023-11-19 04:33 UTC, GlenJeong commented on src/main/java/com/hwamok/user/service/UserServiceImpl.java
> +    }
네 좋은 의견 수렴했습니다.

2023-11-19 04:38 UTC, GlenJeong commented on src/main/java/com/hwamok/user/service/UserServiceImpl.java
> +        userRepository.save(user);
상태 변경이 일어나면 트랜잭션이 커밋될 때 자동으로 DB에 반영되니 save 메소드는 의미가 없어 보이네요 수정했습니다.

2023-11-19 04:41 UTC, GlenJeong commented on src/main/java/com/hwamok/api/UserController.java
> +    @PatchMapping("/update/{id}")
네 의견 수렴하여 수정했습니다.

2023-11-19 04:41 UTC, GlenJeong commented on src/main/java/com/hwamok/api/UserController.java
> +    @DeleteMapping ("/delete/{id}")
네 의견 수렴하여 수정했습니다.

2023-11-19 05:28 UTC, changgyu-kim approved these changes
수고하셧습니다~

2023-11-19 06:03 UTC, goyounha11 commented on src/main/java/com/hwamok/user/service/UserServiceImpl.java
>          User user = userRepository.findById(id).orElseThrow(() -> new RuntimeException("NOT_FOUND_USER"));
@GlenJeong 비지니스 로직에 가깝게 서비스 메소드명을 지어야합니다.
디비 입장에서는 삭제하는 행위일지 몰라도 비지니스 로직이 탈퇴라면 탈퇴가 더 적당할듯합니다.

2023-11-19 10:41 UTC, GlenJeong commented on src/main/java/com/hwamok/user/service/UserServiceImpl.java
>          User user = userRepository.findById(id).orElseThrow(() -> new RuntimeException("NOT_FOUND_USER"));
네 맞네요~ 비즈니스 로직에 맞게 메소드명을 변경했습니다.

2023-11-20 07:59 UTC, goyounha11 approved these changes
고생하셨습니다.

2023-11-20 13:57 UTC, LeeAYoung1207 approved these changes

2023-11-20 14:09 UTC, merged