HM-10 Admin 도메인 수정
Hwamok/Hwamok-api-server pull request #9
Opened 2023-11-17 03:03 UTC by changgyu-kim

1. 필요없는 import 제거
2. 의미없는 공백 제거
3. 테스트코드 의미있는 값 변수로 지정해서 활용

2023-11-17 03:09 UTC, goyounha11 requested changes

2023-11-17 03:09 UTC, goyounha11 commented on src/test/java/com/hwamok/admin/domain/AdminTest.java
> +                .isThrownBy(()-> new Admin("test123","1234","이름",fakeEmail));
```suggestion
        assertThatHwamokException(ExceptionCode.NOT_EMAIL_FORM)
                .isThrownBy(()-> new Admin("test123", "1234", "이름", fakeEmail));
```

2023-11-17 03:09 UTC, goyounha11 commented on src/test/java/com/hwamok/admin/domain/AdminTest.java
> +                .isThrownBy(()-> new Admin("test123","1234","이름",fakeEmail));
다른곳도 다 이렇게 해주시죠

2023-11-17 03:40 UTC, changgyu-kim commented on src/test/java/com/hwamok/admin/domain/AdminTest.java
> +                .isThrownBy(()-> new Admin("test123","1234","이름",fakeEmail));
네 수정했습니다

2023-11-17 09:17 UTC, goyounha11 requested changes

2023-11-17 09:17 UTC, goyounha11 commented on src/test/java/com/hwamok/admin/domain/AdminTest.java
> +                .isThrownBy(()-> new Admin("test123","1234","이름",fakeEmail));
@changgyu-kim 파라미터 사이에 공백 넣으신거 맞나요? 없는데요?

2023-11-17 11:30 UTC, changgyu-kim commented on src/test/java/com/hwamok/admin/domain/AdminTest.java
> +                .isThrownBy(()-> new Admin("test123","1234","이름",fakeEmail));
이해를 잘못했었습니다. 수정했습니다.

2023-11-18 09:23 UTC, goyounha11 approved these changes

2023-11-18 12:24 UTC, GlenJeong commented
고생했어~

2023-11-18 12:25 UTC, GlenJeong approved these changes

2023-11-18 14:53 UTC, merged